### PR TITLE
fix(cli): ensure unknown commands other than help return exit code 1

### LINKED ISSUE #138: Make unknown commands other than "help" return exit code 1

### PR DESCRIPTION
**Pull request by Karan-Palan**
**What kind of change does this PR introduce?**

- Fix: Make unknown commands other than "help" return exit code 1

**Issue Number:**

-  Closes #138 

**Screenshots/videos:**

image

### CODE REVIEW

File: src/main.cc [hunk 1]
```diff
@@ -73,7 +73,8 @@ Global Options:
 For more documentation, visit https://github.com/sourcemeta/jsonschema
 )EOF"};
 
-auto jsonschema_main(const std::string &program, const std::string &command,
+auto jsonschema_main([[maybe_unused]] const std::string &program,
```
Comment (jviotti) [inline src/main.cc]: I don't think you need this annotation. `program` is always used in the help handler!

File: src/main.cc [hunk 2]
```diff
@@ -93,13 +94,17 @@ auto jsonschema_main(const std::string &program, const std::string &command,
...
     return sourcemeta::jsonschema::cli::decode(arguments);
-  } else {
+  } else if (command == "help") {
     std::cout << "JSON Schema CLI - v"
               << sourcemeta::jsonschema::cli::PROJECT_VERSION << "\n";
     std::cout << "Usage: " << std::filesystem::path{program}.filename().string()
               << " <command> [arguments...]\n";
     std::cout << USAGE_DETAILS;
     return EXIT_SUCCESS;
+  } else {
```
Comment (jviotti) [inline src/main.cc:103]: Can you add one test covering this case and the output? See how we test `help` for an example

File: src/main.cc (hunk 1 above)
Comment (Karan-Palan) [reply src/main.cc]: Alright!

File: src/main.cc (hunk 2 above)
Comment (Karan-Palan) [reply src/main.cc:103]: Sure

**Comment by Karan-Palan** [comment]
Did the changes. PTAL

File: test/unknown_command.sh
Comment (jviotti) [inline test/unknown_command.sh:1]: Can you assert the actual error output the CLI prints?

File: test/unknown_command.sh [hunk 3]
```diff
@@ -0,0 +1,27 @@
+#!/bin/sh
+
+set -o errexit
+set -o nounset
+
+TMP="$(mktemp -d)"
+clean() { rm -rf "$TMP"; }
+trap clean EXIT
+
+"$1" unknown_command 1> "$TMP/stdout" 2> "$TMP/stderr" || exit_code=$?
```
Comment (jviotti) [inline test/unknown_command.sh]: Also please see how we do it in other files for consistency. i.e. we use uppercase for variables: `EXIT_CODE`

Comment (jviotti) [reply test/unknown_command.sh]: Also see the `&& EXIT_CODE="$?" || EXIT_CODE="$?"` pattern we use to avoid the `-z` cases you have below

File: test/unknown_command.sh [hunk 4]
```diff
@@ -0,0 +1,27 @@
...
+
+if [ -z "${exit_code:-}" ] || [ "$exit_code" -eq 0 ]; then
```
Comment (jviotti) [inline test/unknown_command.sh]: If you look at other files, we put `then` in its own line. In general, please try to copy the current style as much as possible, otherwise we end up with files that have their own style

File: src/main.cc [hunk 5]
```diff
@@ -93,13 +93,17 @@ auto jsonschema_main(const std::string &program, const std::string &command,
...
+    std::cerr << "error: Unknown command '" << command << "'.\n";
+    std::cerr << "Use '--help' for usage information.\n";
```
Comment (jviotti) [inline src/main.cc]:
```suggestion
    std::cerr << "Use --help for usage information\n";
```

For consistency

File: src/main.cc [hunk 6]
```diff
@@ -93,13 +93,17 @@ auto jsonschema_main(const std::string &program, const std::string &command,
...
-  } else {
+  } else if (command == "help") {
     std::cout << "JSON Schema CLI - v"
               << sourcemeta::jsonschema::cli::PROJECT_VERSION << "\n";
     std::cout << "Usage: " << std::filesystem::path{program}.filename().string()
               << " <command> [arguments...]\n";
     std::cout << USAGE_DETAILS;
     return EXIT_SUCCESS;
+  } else {
+    std::cerr << "error: Unknown command '" << command << "'.\n";
```
Comment (jviotti) [inline src/main.cc]:
```suggestion
    std::cerr << "error: Unknown command '" << command << "'\n";
```

For consistency with all other error messages

**Comment by Karan-Palan** [comment]
Done the required changes, ptal

**Comment by jviotti** [comment]
Awesome, thanks a lot!
